# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: x265 GUI Encoder with Internet Friendly Media Encoder!
email: your-email@domain.com
description: Shrink video up to half the original size while maintaining highest possible quality compared previous generation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://x265.github.io" # the base hostname & protocol for your site
twitter_username: Anime4000
github_username:  Anime4000

# Build settings
markdown: kramdown
